### ISSUE TITLE
Replay on Mock Device

### ISSUE THREAD

**Issue by kevincar** [umnil/abmbci#10]
**Describe the solution you'd like**
The Mock device currently returns random raw data. It would be nice if the mock device could take a list of `edf` files that could be used to reproduce sampling.

**Describe alternatives you've considered**
none

**Comment by kevincar** [comment]
Resolved

**Comment by kevincar** [comment]
Reopening because after sampling for a moment, the following error is obtained:

```
ERROR:tornado.application:Exception in callback <bound method TimerBase._on_timer of <matplotlib.backends.backend_webagg_core.TimerTornado object at 0x30f9be370>>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/bcifest/lib/python3.9/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/bcifest/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1233, in _on_timer
    ret = func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/bcifest/lib/python3.9/site-packages/matplotlib/animation.py", line 1427, in _step
    still_going = super()._step(*args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/bcifest/lib/python3.9/site-packages/matplotlib/animation.py", line 1121, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/bcifest/lib/python3.9/site-packages/matplotlib/animation.py", line 1140, in _draw_next_frame
    self._draw_frame(framedata)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/bcifest/lib/python3.9/site-packages/matplotlib/animation.py", line 1768, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/var/folders/vn/ps4sm2p50zx0y48wlgtyhsgh0000gn/T/ipykernel_50594/1034804548.py", line 89, in update
    next_x = headset.get_raw_data().T[6:-4]
  File "/opt/homebrew/Caskroom/miniconda/base/envs/bcifest/lib/python3.9/site-packages/abmbci/testheadset.py", line 265, in get_raw_data
    data: np.ndarray = self.sample_data()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/bcifest/lib/python3.9/site-packages/abmbci/testheadset.py", line 331, in sample_data
    data = np.c_[metadata, main_data.T]
  File "/opt/homebrew/Caskroom/miniconda/base/envs/bcifest/lib/python3.9/site-packages/numpy/lib/index_tricks.py", line 418, in __getitem__
    res = self.concatenate(tuple(objs), axis=axis)
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3205 and the array at index 1 has size 3
```
